# See https://prek.j178.dev/quickstart/ for more information
[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
    {id = "trailing-whitespace"},
    {id = "name-tests-test"},
    {id = "end-of-file-fixer"},
    {id = "requirements-txt-fixer"},
    {id = "check-json"},
    {id = "check-yaml"},
    {id = "check-ast"},
    {id = "check-added-large-files"},
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.8"
hooks = [
    {id = "ruff", args = ["--fix", "src", "tests"]},
    {id = "ruff-format", args = ["src", "tests"]},
]

[[repos]]
repo = "https://github.com/Lucas-C/pre-commit-hooks-bandit"
rev = "v1.0.6"
hooks = [
    {id = "python-bandit-vulnerability-check", args = ["--skip", "B101", "--severity-level", "medium", "--recursive", "src"]}
]

[[repos]]
repo = "https://github.com/pre-commit/pygrep-hooks"
rev = "v1.10.0"
hooks = [{id = "python-no-eval"}]

[[repos]]
# Use mirror to avoid autoupdate issue: https://github.com/crate-ci/typos/issues/390
repo = "https://github.com/adhtruong/mirrors-typos"
rev = "v1.44.0"
hooks = [{id = "typos"}]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = 'v2.4.2'
hooks = [{id = "codespell", files = ".(py|rst|md)$", args = ["--ignore-words-list=ser"] }]

[[repos]]
repo = "https://github.com/adamchainz/blacken-docs"
rev = "1.20.0"
hooks = [{id = "blacken-docs", args = ["--skip-errors"], additional_dependencies = ["black==22.12.0"]}]
