name: PR Checks

on:
  pull_request:
    branches:
    - main

jobs:

  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: "true"
          cache-dependency-glob: "pyproject.toml"
      - name: Install & run ruff linter and formatter
        run: |
          uvx ruff version
          uvx ruff format iso_week_date tests --diff
          uvx ruff check iso_week_date tests --output-format=github
          uvx ruff clean

  slotscheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: "true"
          cache-dependency-glob: "pyproject.toml"
      - name: Install & run slotscheck
        run: uv run --all-extras --group slotscheck slotscheck -m iso_week_date

  test:
    env:
      PYTHONHASHSEED: 42
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]  # TODO: 3.14 raises because of pydantic?
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: "true"
          cache-suffix: ${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"
      - name: Install dependencies and run tests
        run: |
          uv run --all-extras --group tests pytest --cov=iso_week_date --cov=tests --cov-fail-under=80
          uv run --all-extras --group tests pytest iso_week_date --doctest-modules

  test-free-threaded:
    strategy:
      matrix:
        python-version: ["3.13t", "3.14t"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install base and run tests (no extra deps)
        run: |
          uv run --group tests pytest -m "not pandas and not polars and not pydantic"
          uv run --group tests pytest -m "freethreaded" --parallel-threads=4 --iterations=10

  doc-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: "true"
          cache-dependency-glob: "pyproject.toml"
      - name: Install dependencies and check docs can build
        run: uv run --group docs mkdocs build -v -s
